# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    # The type of runner that the job will run on
    runs-on: [macos-12]

    steps:
      - name: xcode-select
        run: sudo xcode-select --switch /Applications/Xcode_14.1.app
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Test
        run: |
          xcodebuild test \
          -scheme OWOWKit-Package \
          -destination "name=iPhone 12,OS=latest" \
          | xcpretty && exit ${PIPESTATUS[0]}
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
